name: Ruby

on:
  push:
    branches:
    - master
  pull_request:
    paths-ignore:
    - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
        - 2.4
        - 2.6
        - 2.7

    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: ${{ matrix.ruby }}

    - run: bundle exec rake
